on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt

      - name: Run bot
        run: |
          python bot.py
