name: Run Discord Bot

on:
  schedule:
    - cron: "00:00 * * *"  # รันทุกๆ 00:00 น.
    - cron: "08:00 * * *"  # รันทุกๆ 08:00 น.
    - cron: "16:00 * * *"  # รันทุกๆ 16:00 น.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      run: |
        python bot.py --log-level=INFO

