name: Run Discord Bot with All Features

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.local/pip/cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  build-docker-image:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t discord-bot:latest .

  test:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
    - name: Run tests from Docker image
      run: |
        docker run -it discord-bot:latest python -m unittest discover

  run:
    needs: [setup, build-docker-image, test]
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - name: Run bot from Docker image
      run: |
        docker run -it discord-bot:latest

