name: Run Python Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ตั้งค่า Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: ติดตั้ง dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: เรียกใช้ bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Replace with your actual secret name
      run: |
        pm2 start bot.py --log-level=INFO

    - name: Save logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs/*.log
